#ifndef VIEWOBJECTTYPE_H
#define VIEWOBJECTTYPE_H

enum class eViewObjectType
{
	OBJECT_TYPE_SPRITE = 0,
	OBJECT_TYPE_LABEL,
	OBEJCT_TYPE_BUTTON,
	OBJECT_TYPE_POP_UP_LAYER
};

#endif //VIEWOBJECTTYPE_H
